// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxigtrpkjyrxsalbdxwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4aWd0cnBranlyeHNhbGJkeHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjA3MjMsImV4cCI6MjA2ODIzNjcyM30.0jI6MlT9C4iQ0kyPDAZ6sKbV1x8l572y_E7tPTMsyIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});